spring:
  datasource:
    url: jdbc:mysql://localhost:3306/people-sync  # Substitua 'nome_do_banco' pelo nome do seu banco de dados
    username: root                                  # Substitua 'root' pelo nome de usuário do banco de dados
    password: "@Kiryto1420*"                               # Substitua 'senha' pela senha do banco de dados
    driver-class-name: com.mysql.cj.jdbc.Driver     # Driver para MySQL

  jpa:
    hibernate:
      ddl-auto: update                              # Usado para criar/atualizar automaticamente as tabelas no banco
    show-sql: true                                  # Para exibir as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialeto para MySQL

server:
  port: 8080  # Porta padrão do Spring Boot
